### PR TITLE
Add ability to use headers from `Vary` as part of cache keys

### LINKED ISSUE #112: Cache entries can grow unbounded
Initially reported in https://github.com/Shopify/shipit-engine/issues/935 by @josacar

### Context

Shipit is a deploy tool, as such it's frequently hitting the same endpoint to grab updates, e.g `GET https://api.github.com/v3/repos/my-org/my-repo/commits?branch=master`.

Additionally it uses the GitHub App api for authentication, so it's `Authorization` header changes every hour.

And finally GitHub's API responses specify the following `Vary` header: `Accept, Authorization, Cookie, X-GitHub-OTP`.

### Problem

Since the URL never changes, the same cache entry is re-used all the time. However since the `Authorization` token change every hour, new entries are regularly prepended, until the cache entry becomes huge, and start taking a lot of time to be deserialized, or even go over the cache store size (memcached limit values to 1MB).

### Solutions

I can see several solutions to this, with very different tradeoffs.

#### Very simple, set a cap on the number of entries per key

Self explanatory, we could simply set a configurable upper limit on the number of entries, and drop the oldest entry whenever we go over.

It's an easy fix, not quite ideal as it might surprise people, but IMHO it's better to be surprised by cache evictions than by cache OOM / corruption (in case of memcache truncation).

#### Somewhat simple, evict stale entries

When prepending a new entry, we could evict all the stale ones. It's easy if `max-age / Expires` is set, if it isn't, then we have to rely on [heuristics as specify in the RFC](https://tools.ietf.org/html/rfc7234#section-4.2.2)

#### Harder, and potentially slower, store varying responses under different keys

Since `Faraday::HttpCache` implicitly relies on the underlying cache store for garbage collection, the idea here would be to store individual responses under different keys, so that rarely accessed ones can be garbage collected.

The very tricky part is that the `Vary` is in the response, so it means maintaining some kind of non-trivial index of what kind of `Vary` values were returned for that response, and then use that to select a good candidate for revalidation.

Additionally it means that it will at least double the number of cache lookups, which is not a small downside.

cc @rafaelfranca @Edouard-Chin @josacar

### PR DESCRIPTION
**Pull request by skryukov**
The initial problem: we use GitHub API and to save on API limits we want to use HTTP caching, but with the current `Faraday::HttpCache::Storage` implementation (one cache key per URL) caching of GitHub API endpoints like `https://api.github.com/user` is impossible since for every request we are fetching an array of all requests for all our users. Limiting the number of cached entries per key from #121 is also not an option in this case.

So, the only way to cache GitHub API for us is implementing different storage strategy. That is what this PR is about.

This PR Introduced a new `strategy` option to support different cache storage strategies:
- The original strategy was moved from `Faraday::HttpCache::Strage` to `Faraday::HttpCache::Strategies::ByUrl`.
- The new `Faraday::HttpCache::Strategies::ByVary` strategy uses headers from `Vary` header to generate cache keys. It also uses the index with `Vary` headers mapped to the request URL.
- `Faraday::HttpCache::Strage` class was deprecated.

This PR also:
- drops support for Ruby < 2.4
- adds support for Ruby 2.7, 3.0, 3.1
- introduces GitHub Actions
- updates Rubocop

This PR is a successor for #122
Related #112

### CODE REVIEW

**Comment by garaujodev** [comment]
Thanks for the PR ❤️💜💙💛💚🖤

I'll take a look as soon as possible!

**Comment by garaujodev** [comment]
I'm assuming as maintainer for this gem. For my first releases, and to be in compliance with Semantic Version standards, I intend to be more conservative on releases.

I think that a good idea to reach it, is split this PR into 3 PRs:

- Introduce GitHub Actions and Update Rubocop
- Add support for Ruby 3.0 (I'll release it as a patch version)
- Introduce cache strategy feature (I'll release it as a minor version)

@skryukov what do you think about? Could you split this PR into 3 mentioned PRs? 

Please just let me know if you need help to do that.

**Comment by skryukov** [comment]
@garaujodev sounds fine.

What about support for ruby `< 2.4`? I believe the gem is still capable of supporting them (not sure about the strategies part though), we only need to downgrade some dev dependencies (including rubocop) to enable the test suite.

But is that worth the headache?

**Comment by garaujodev** [comment]
@skryukov I was thinking about it, because support for [Ruby 2.4 was ended in 2020](https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/).

With that, I'm planning to release in this way (Current version: `2.2.0`):

- Ruby 3 support and deprecate Ruby 2.4 -> `2.3.0`
- Cache strategy -> `2.4.0`

So, we can deprecate Ruby 2.4 in the same PR that introduce Ruby 3 support.

**Comment by skryukov** [comment]
Closing in favor of #128 #129 and #130

**Pull request closed without merging**
